version: 0.9.4{build}
image: Visual Studio 2022
configuration: Release
build:
  verbosity: minimal
after_build:
- cmd: 7z a TinyFinder.zip .\TinyFinder\bin\Release\TinyFinder.exe
artifacts:
- path: TinyFinder.zip
  name: TinyFinder
