using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TinyFinder.Controls
{
    class Move
    {
        public string Name { get; set; }
        public int At { get; set; }

        public static List<string> ManualLearnMoves = new List<string>
        {
            "Hone Claws",
            "Dragon Claw",
            "Psyshock",
            "Calm Mind",
            "Roar",
            "Toxic",
            "Hail",
            "Bulk Up",
            "Venoshock",
            "Hidden Power",
            "Sunny Day",
            "Taunt",
            "Ice Beam",
            "Blizzard",
            "Hyper Beam",
            "Light Screen",
            "Protect",
            "Rain Dance",
            "Roost",
            "Safeguard",
            "Frustration",
            "Solar Beam",
            "Smack Down",
            "Thunderbolt",
            "Thunder",
            "Earthquake",
            "Return",
            "Dig",
            "Psychic",
            "Shadow Ball",
            "Brick Break",
            "Double Team",
            "Reflect",
            "Sludge Wave",
            "Flamethrower",
            "Sludge Bomb",
            "Sandstorm",
            "Fire Blast",
            "Rock Tomb",
            "Aerial Ace",
            "Torment",
            "Facade",
            "Flame Charge",
            "Rest",
            "Attract",
            "Thief",
            "Low Sweep",
            "Round",
            "Echoed Voice",
            "Overheat",
            "Steel Wing",
            "Focus Blast",
            "Energy Ball",
            "False Swipe",
            "Scald",
            "Fling",
            "Charge Beam",
            "Sky Drop",
            "Incinerate",
            "Quash",
            "Will-O-Wisp",
            "Acrobatics",
            "Embargo",
            "Explosion",
            "Shadow Claw",
            "Payback",
            "Retaliate",
            "Giga Impact",
            "Rock Polish",
            "Flash",
            "Stone Edge",
            "Volt Switch",
            "Thunder Wave",
            "Gyro Ball",
            "Swords Dance",
            "Struggle Bug",
            "Psych Up",
            "Bulldoze",
            "Frost Breath",
            "Rock Slide",
            "X-Scissor",
            "Dragon Tail",
            "Infestation",
            "Poison Jab",
            "Dream Eater",
            "Grass Knot",
            "Swagger",
            "Sleep Talk",
            "U-turn",
            "Substitute",
            "Flash Cannon",
            "Trick Room",
            "Wild Charge",
            "Secret Power",
            "Snarl",
            "Nature Power",
            "Dark Pulse",
            "Power-Up Punch",
            "Dazzling Gleam",
            "Confide",
            "Cut",
            "Fly",
            "Surf",
            "Strength",
            "Waterfall",
            "Rock Smash",
            "Dive",
            "Bug Bite",
            "Covet",
            "Super Fang",
            "Dual Chop",
            "Signal Beam",
            "Iron Head",
            "Seed Bomb",
            "Drill Run",
            "Bounce",
            "Low Kick",
            "Gunk Shot",
            "Uproar",
            "Thunder Punch",
            "Fire Punch",
            "Ice Punch",
            "Magic Coat",
            "Block",
            "Earth Power",
            "Foul Play",
            "Gravity",
            "Magnet Rise",
            "Iron Defense",
            "Last Resort",
            "Superpower",
            "Electroweb",
            "Icy Wind",
            "Aqua Tail",
            "Dark Pulse",
            "Zen Headbutt",
            "Dragon Pulse",
            "Hyper Voice",
            "Iron Tail",
            "Bind",
            "Snore",
            "Knock Off",
            "Synthesis",
            "Heat Wave",
            "Role Play",
            "Heal Bell",
            "Tailwind",
            "Sky Attack",
            "Pain Split",
            "Giga Drain",
            "Drain Punch",
            "Roost",
            "Focus Punch",
            "Shock Wave",
            "Water Pulse",
            "Gastro Acid",
            "Worry Seed",
            "Spite",
            "After You",
            "Helping Hand",
            "Trick",
            "Magic Room",
            "Wonder Room",
            "Endeavor",
            "Outrage",
            "Recycle",
            "Snatch",
            "Stealth Rock",
            "Sleep Talk",
            "Skill Swap",
        };
    }
}
